### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by andy500** [aim-uofa/AdelaiDepth#11]
keep getting this  ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi' when l run python ./tools/test_depth.py --load_ckpt res50.pth --backbone resnet50  why?

**Comment by andy500** [comment]
got it to work

**Comment by EllieFar** [comment]
Hi Thanks for your nice work. I tried to run AdelaiDepth_ResNet101.ipynb
([here](https://github.com/aim-uofa/AdelaiDepth/blob/main/AdelaiDepth_ResNet101.ipynb)) but I got error like: 


/env/python:/content/AdelaiDepth/LeReS:/content/AdelaiDepth/LeReS:/content/AdelaiDepth/LeReS:/content/AdelaiDepth/LeReS:/content/AdelaiDepth/LeReS
/content/AdelaiDepth
Traceback (most recent call last):
  File "/content/AdelaiDepth/LeReS/Minist_Test/tools/test_depth.py", line 19, in <module>
    from lib.multi_depth_model_woauxi import RelDepthModel
ModuleNotFoundError: No module named 'lib'



I tried below solution mentioned [here](https://github.com/aim-uofa/AdelaiDepth/issues/11#issuecomment-953388438). but still didn't work. 

```
import sys, os
sys.path.insert(1, os.getcwd()) 
```


I also tried below solution metioned [here](https://github.com/aim-uofa/AdelaiDepth/issues/7), but did not work

```
import os
import sys
sys.path.insert(1, os.path.abspath(".")) # insert the current directory 
from lib.multi_depth_model_woauxi import RelDepthModel
from lib.net_tools import load_ckpt
```

Do you have any idea how can I solve it? I would appreciate it.
