### ISSUE TITLE
module 'torchsparse_backend' has no attribute 'hash_forward

### ISSUE THREAD

**Issue by LeonardoCBoar** [aim-uofa/AdelaiDepth#12]
Hi!

I'm having this problem here with and import statement from Torchsparse(version 1.2.0 as fixed in the last commit):
`module 'torchsparse_backend' has no attribute 'hash_forward`
I tried to ask the solution on Torchsparse repo, but they ask to update to 1.4.0, but that version breaks a lot of other import statements.

Does anyone know the solution?

Thanks in advance!

**Comment by YvanYin** [comment]
I am using the version: 1.0.0. Could you try this version?

**Comment by LeonardoCBoar** [comment]
Thanks a lot! It worked now with 1.0.0!

**Comment by yunus-topal** [comment]
@YvanYin  I installed LeReS with instruction in ReadMe file. When i try to  install torchsparse1.0.0 i get this error message (I used wsl2 ubuntu):

> ERROR: Command errored out with exit status 1:
     command: /home/emretopal20/anaconda3/envs/LeReS/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ams6fp0r/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ams6fp0r/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-angxfe25
         cwd: /tmp/pip-req-build-ams6fp0r/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ams6fp0r/setup.py", line 67, in <module>
        extra_compile_args=extra_compile_args)
      File "/home/emretopal20/anaconda3/envs/LeReS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 779, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/home/emretopal20/anaconda3/envs/LeReS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 869, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/home/emretopal20/anaconda3/envs/LeReS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1783, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
WARNING: Discarding git+https://github.com/mit-han-lab/torchsparse.git@v1.0.0. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I tried to set my cuda home like this:
> export CUDA_HOME=/home/emretopal20/anaconda3/pkgs/cudatoolkit-10.2.89-hfd86e86_

then i got this error:

>   ERROR: Command errored out with exit status 1:
   command: /home/emretopal20/anaconda3/envs/LeReS/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ob_ybiz2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ob_ybiz2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7y9n298d
       cwd: /tmp/pip-req-build-ob_ybiz2/

**Comment by yunus-topal** [comment]
i set up the model on google colab and now i can use it. No need to worry about this error.

**Comment by marissachanlatte** [comment]
Hi, 

I am having the same issue as @yunus-topal, but I wasn't able to get the shape demo working on colab (only the depth demo). Any suggestions? 

Thanks!
