### ISSUE TITLE
Depth recovery issue

### ISSUE THREAD

**Issue by jing98tian** [aim-uofa/AdelaiDepth#13]
Thank you for your contribution. In the same scene, the change of camera attitude will lead to the scale recovery parameter a, and b will also change accordingly. Is it possible to recover more robust scale parameters for the same scene?

**Comment by YvanYin** [comment]
Hi, I have not tested the scale consistency problem.  Did you use our method on a video?

**Comment by jing98tian** [comment]
Yes, it's tested on a video in realtime. And i use the relsense d435i to get the true depth value to reacover the scale parameter.
 In the case of camera motion, the scale gray parameter is not robust enough. Should the true depth value be used to estimate the scale recovery parameter all the time?

**Comment by YvanYin** [comment]
I believe that you can use some sparse points that have known depth to recover the scale and shift for the predictions for each frame. Our method doesn't optimize the scale consistency.

**Comment by guangkaixu** [comment]
@jing98tian Hi, if you can obtain some sparse depth points, you may be interested in this work: https://github.com/guangkaixu/BoostingDepth, which leverages sparse points to ensure depth consistency between frames.
