### ISSUE TITLE
Is it possible to obtain distance in meters?

### ISSUE THREAD

**Issue by liujiaxing7** [aim-uofa/AdelaiDepth#16]

**Comment by liujiaxing7** [comment]
Hi, I was wondering it is possible to obtain a metric depth map using this network.
Thank you in advance.

**Comment by YvanYin** [comment]
hi,
our method can only provide an affine-invariant depth. However, if you have several sparse points with metric depth values (in meters), you can align the prediction with these points to get the metric depth.

**Comment by liujiaxing7** [comment]
Ok thanks, i try to do it.

**Comment by dimasheva1** [comment]
@liujiaxing7 Did you get some results?Is it possible obtain a real distance?

**Comment by guangkaixu** [comment]
@liujiaxing7 @dimasheva1 Hi, the ground truth depth is required if you want to recover metric depth. The code is released at https://github.com/aim-uofa/AdelaiDepth/blob/de906b4ac4ad5775daedaf443fcff02a994188a0/LeReS/Train/lib/utils/evaluate_depth_error.py#L7. 

Also, if you have some sparse ground truth points only, you may be interested in the local recovery strategy at https://github.com/guangkaixu/BoostingDepth.
