### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by caigx111** [aim-uofa/AdelaiDepth#18]
Hi, Could you please provide the training code?

**Comment by ttsesm** [comment]
@YvanYin any update regarding publishing the training code, I would also be interested to that as quite a few my guess is in the community.

Thanks

**Comment by YvanYin** [comment]
Hi, I will discuss with my Adobe coauthors about traning code. There are some IP issues. I want to release them.

**Comment by ttsesm** [comment]
Thanks @YvanYin, looking forward to an update asap.

**Comment by ttsesm** [comment]
@YvanYin any update on this?

**Comment by elliestath** [comment]
hey, great paper! We are interested in training on our own data, will the code be eventually available? Pre-trained weights would also be very helpful.

**Comment by YvanYin** [comment]
I have rele

**Comment by elliestath** [comment]
Hey, cool, thank you so much, will test it asap. I saw it's the code on virtual normal and diverse depth projects. Is there any plan to release also the respective code for "Learning to recover 3D Scene Shape from a Single Image"?

**Comment by YvanYin** [comment]
Hey, most of the training code of LeReS is the same as DiverseDepth except for training data and some losses. I am still solving the IP issues, you know:) I will try to release them ASAP.

**Comment by ayman-saleh** [comment]
Are the differences in training data specific to the PCM, or is the DPM also trained on a separate dataset relative to DiverseDepth?

**Comment by guangkaixu** [comment]
@caigx111 @ttsesm @elliestath @ayman-saleh Hi, the training code of LeReS is released today.
