### ISSUE TITLE
May I ask for the code to calculate the WHDR metric as per table 5 in the paper?

### ISSUE THREAD

**Issue by Oreobun** [aim-uofa/AdelaiDepth#26]
![table5](https://user-images.githubusercontent.com/55806893/146641372-21f152f1-9c5f-46c3-812d-3f614ecacd4a.JPG)

I have found the paper that introduces the WHDR metric from [Intrinsic Images in the Wild](http://opensurfaces.cs.cornell.edu/publications/intrinsic/) but a human judgment JSON file is required using the code provided. May I ask for the evaluation code for datasets such as the OASIS YT3D/DIODE or a guide on how to compute the WHDR metric from the ground truth depth map and prediction depth map?

**Comment by YvanYin** [comment]
def weighted_human_disagreement_rate(gt, pred):
    p12_index = select_index(gt)
    gt_reshape = np.reshape(gt, gt.size)
    pred_reshape = np.reshape(pred, pred.size)
    mask = gt > 0
    gt_p1 = gt_reshape[mask][p12_index['p1']]
    gt_p2 = gt_reshape[mask][p12_index['p2']]
    pred_p1 = pred_reshape[mask][p12_index['p1']]
    pred_p2 = pred_reshape[mask][p12_index['p2']]

    p12_rank_gt = np.zeros_like(gt_p1)
    p12_rank_gt[gt_p1>gt_p2] = 1
    p12_rank_gt[gt_p1<gt_p2] = -1

    p12_rank_pred = np.zeros_like(gt_p1)
    p12_rank_pred[pred_p1>pred_p2] = 1
    p12_rank_pred[pred_p1<pred_p2] = -1

    err = np.sum(p12_rank_gt != p12_rank_pred)
    valid_pixels = gt_p1.size
    return err, valid_pixels


def select_index(gt_depth, select_size=10000):
    valid_size = np.sum(gt_depth>0)
    try:
        p = np.random.choice(valid_size, select_size*2, replace=False)
    except:
        p = np.random.choice(valid_size, select_size*2*2, replace=True)
    np.random.shuffle(p)
    p1 = p[0:select_size*2:2]
    p2 = p[1:select_size*2:2]

    p12_index = {'p1': p1, 'p2': p2}
    return p12_index

whdr_err_sum, eval_num = weighted_human_disagreement_rate(gt_scale, pred_scale)
err = whdr_err_sum / eval_num
