### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by srikanth-midde** [aim-uofa/AdelaiDepth#27]
```
processing (0000)-th image... ./test_images/.ipynb_checkpoints
Traceback (most recent call last):
  File "./tools/test_shape.py", line 111, in <module>
    rgb_c = rgb[:, :, ::-1].copy()
TypeError: 'NoneType' object is not subscriptable
```

Though I have I uploaded the images in the test_images folder but I am getting  "None Type" error.

I am facing the above error while I am executing the Test 3D reconstruction from a single image. Can anyone help me to sort out this issue.

Thanks in Advance.

**Comment by YvanYin** [comment]
Could you check the path for reading RGB image? It seems that it cannot find the RGB image.

**Comment by srikanth-midde** [comment]
The path of the RGB image is correct and these images are in test_images folder but I am getting the same error. I double checked it. This is happening when we are trying to test the 3D reconstruction from a single image with our own images. 

Thanks,

**Comment by srikanth-midde** [comment]
I tried to check the RGB path and it has images in the folder but still I am getting the  same  error (TypeError: 'NoneType' object is not subscriptable).

 Also I tried to debug the whole code step by step right from starting.

I am sorry to say Issue has not been resolved.

Thanks,

**Comment by YvanYin** [comment]
Hi,
Could you directly replace the RGB path with a fixed absolute path for loading? If this still cannot work, it means there are some issues with your env setting.

**Comment by srikanth-midde** [comment]
Hi, 

I tried it previously  to replace the direct path for RGB in the code but it is not helpful for me .

I got the same error (TypeError: 'NoneType' object is not subscriptable). 

Thanks,

**Comment by YvanYin** [comment]
I believe that this is not the issue of the code, because you have set the path for loading. This means that the code cannot find the path. Have you set the PATHONPATH?

**Comment by srikanth-midde** [comment]
yes,, I changed it....

I too believe that your code has no issue with the code but there is some environment issue in Google Colab.

I got the 3D scene shape test result for 2 times but then after when I  tried to test it is showing this error.

**Comment by YvanYin** [comment]
Maybe we can do another test first. You can create a new script in your env (at the same location as my test_shape.py), then you try to load and write images in this new script.
