### ISSUE TITLE
Question on regression loss

### ISSUE THREAD

**Issue by mzy97** [aim-uofa/AdelaiDepth#3]
what is the difference between "Image-level normalized regression loss" and shift_scale invariant loss based on median of a sample in <Towards Robust Monocular Depth Estimation: Mixing Datasets for Zero-shot Cross-dataset Transfer> (MiDaS). And what is the benefit of your proposed loss compared to MiDaS's.

**Comment by YvanYin** [comment]
Our Image-level regression loss only need to normalize the ground truth depth. By contrast, MiDaS has to processing both the ground truth and predicted depth. The process can be the normalization or  least square fitting. According to our ablation studies, our loss can achieve better performance.

**Comment by YvanYin** [comment]
MiDaS loss has to adjust both the ground truth and prediction to a similar numerical range. I am conjunct that such adjustment may  be not that stable.
