### ISSUE TITLE
where can I find the code for paper <Boosting Monocular Depth Estimation with Sparse Guided Points>

### ISSUE THREAD

**Issue by ruolinsss** [aim-uofa/AdelaiDepth#30]
Hi, I am interested in the Locally Weighted Linear Regression method in paper Boosting Monocular Depth Estimation with Sparse Guided Points. Where can I find this part code?

**Comment by YvanYin** [comment]
We will release the code under this project later.

**Comment by maliksyria** [comment]
any updates on this please @YvanYin
