### ISSUE TITLE
Test monocular depth prediction error

### ISSUE THREAD

**Issue by semel1** [aim-uofa/AdelaiDepth#31]
Running 
`python ./tools/test_depth.py --load_ckpt res50.pth --backbone resnet50 `
or 
`python ./tools/test_depth.py --load_ckpt res101.pth --backbone resnext101`

throws an error:
```
F:\Depth_estimation\AdelaiDepth-main\LeReS>python ./tools/test_depth.py --load_ckpt res50.pth --backbone resnet50
Traceback (most recent call last):
  File "./tools/test_depth.py", line 1, in <module>
    from lib.multi_depth_model_woauxi import RelDepthModel
ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'

F:\Depth_estimation\AdelaiDepth-main\LeReS>python ./tools/test_depth.py --load_ckpt res101.pth --backbone resnext101
Traceback (most recent call last):
  File "./tools/test_depth.py", line 1, in <module>
    from lib.multi_depth_model_woauxi import RelDepthModel
ModuleNotFoundError: No module named 'lib.multi_depth_model_woauxi'
```

**Comment by YvanYin** [comment]
Have you added the PYTHONPATH?

**Comment by semel1** [comment]
Yes, add PYTHONPATH did the job.
Unfortunately I couldn't manage to install  'torchsparse' in my Windows 10 environment. 
Is there is solution for that other than install WSL?

**Comment by YvanYin** [comment]
Could you please try Linux system? I have never tried Windows. For more details about installing torchsparse, please refer to torchsparse Github repo.
