### ISSUE TITLE
Result not satisfactory

### ISSUE THREAD

**Issue by JohnG0024** [aim-uofa/AdelaiDepth#32]
Hi Yin, 
I just tested one of my images, but the result is less satisfactory compared to that of your research paper. Would it be possible for you to take a look and investigate on the cause? Thank you.
![33](https://user-images.githubusercontent.com/70065447/155493212-f0062947-91c4-4434-a66a-7362289e14e0.png)
![33-depth_raw](https://user-images.githubusercontent.com/70065447/155493224-9cba1162-f496-4732-be96-2d2341dd0598.png)

**Comment by YvanYin** [comment]
Hi, it seems that your testing images are synthetic images, which do not have any background information. I have never trained the model on such data, so it cannot work well.

**Comment by caiyongqi** [comment]
> 嗨，尹， 我刚刚测试了我的一张图片，但与你的研究论文相比，结果不太令人满意。是否可以让您查看并调查原因？谢谢你。 ![33](https://user-images.githubusercontent.com/70065447/155493212-f0062947-91c4-4434-a66a-7362289e14e0.png) ![33-depth_raw](https://user-images.githubusercontent.com/70065447/155493224-9cba1162-f496-4732-be96-2d2341dd0598.png)
Hi, John. Have you found a model that accurately predicts depth in synthetic images?

**Comment by YvanYin** [comment]
Hi Cai,

This image is a synthetic image, and our model has not been trained on them. You can try other depth prediction methods trained on such photos, no background information, and replace them with my depth model. The reconstruction will be much better.
