### ISSUE TITLE
Obtaining ground-truth focal length

### ISSUE THREAD

**Issue by ayman-saleh** [aim-uofa/AdelaiDepth#34]
Hello,

Upon reading your paper, in order to generate the training samples for the PCM, on the fly you perturb the focal length by some delta, then generate the point cloud. It seems that the diverse depth dataset does not have the focal length in the annotations. Is this information not yet released?

Thanks

**Comment by YvanYin** [comment]
Hi,
The released DiverseDepth dataset is for DiverseDepth project. Please see the paper "Virtual Normal: Enforcing Geometric Constraints for Accurate and Robust Depth Prediction" and "diversedepth: affine-invariant depth prediction using diverse data" for details. If you want to get more details of PCM module, please see the paper "Learning to recover 3D scene shape from a single image".
