### ISSUE TITLE
Preprocessing Depth Data and Auxiliary Branch Architecture

### ISSUE THREAD

**Issue by PJ-cs** [aim-uofa/AdelaiDepth#37]
Hello, thank you for your amazing work!

I am trying to reproduce your training procedure.
And I have two questions regarding the preprocessing
and the architecture of the lightweight branch.

If I understand correctly, you trained your network
with two branches, one main branch for relative depth
estimation and one auxiliary branch for disparity estimation.
Each with different losses depending on the used dataset.

1. Preprocessing:
   - Did you apply any preprocessing to the relative depth sources
     taskonomy and 3dkenburns  ?
   - How did you normalize the disparity?
   - Did you specifically handle sky regions by using segmentation masks?

2. Auxiliary Branch:
   - It seems to be a central part of the training procedure, but you
     only give general information in the appendix.
   - What architecture did you use for this branch? Does it only share 
      the weights of the first 4 layers of the decoder and adds a new
      last layer for the disparity estimation?

Thank you for your time and
Best Regards

**Comment by guangkaixu** [comment]
@PJ-cs Hi, the relative depth and disparity are normalized to 0-10. Some extremely large values of taskonomy and 3dkenburns are masked before normalization. You can generate sky masks with the help of existing segmentation methods. 

The training code of LeReS is released today. For more information, you can check the code for details.
