### ISSUE TITLE
Whether this loss can be used directly to calculate disparity loss

### ISSUE THREAD

**Issue by aiforworlds** [aim-uofa/AdelaiDepth#38]
Hello, thank you for your amazing work!

I want to kown whether  (PWNPlanesLoss、EdgeguidedNormalRegressionLoss、MSGIL_NORM_Loss)loss can be used directly to calculate disparity loss, because my dataset is disparity data not depth data.

Thank you for your time 
Best Regards

**Comment by guangkaixu** [comment]
Hello@aiforworlds, you can train with gt disparity by providing annotations like: ```[{"rgb_path": "folder/rgb/0.jpg", "disp_path": "folder/disp/0.png"}, ...]``` , where disp_path is the path of gt disparity image. The disparity will be converted to depth in multi_dataset.py (https://github.com/aim-uofa/AdelaiDepth/blob/6309e00ae56b8fc74a52431f76d8e18633351c70/LeReS/Train/data/multi_dataset.py#L332).
