### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lw0210** [aim-uofa/AdelaiDepth#39]
Dear,where is the 'Holopix50k/annotations/val_annotations.json'?    I only get Holopix50k/annotations/all_annotations.json  after I run the command 'sh download_data.sh'.

**Comment by lw0210** [comment]
Thank you for your reply！
Yes, I am running the latest script, but the error message shows no /annotations/all_ annotations. json.I also checked that it was not. I am running sh Download_ data. Is this  correct ?
是的，我运行的是最新的脚本，但是报错显示没有/annotations/all_annotations.json .我也检查了，确实找不到那个json文件，我是运行sh download_data.sh下载的数据集，请问这是正确的吗？ @yaochx

**Comment by guangkaixu** [comment]
@lw0210 Hi, the val_annotations.json of Holopix50k is not supplied. Please remove all datasets without val_annotations.json in https://github.com/aim-uofa/AdelaiDepth/blob/6309e00ae56b8fc74a52431f76d8e18633351c70/LeReS/Train/tools/train.py#L256.  I will fix the bug right now.

**Comment by lw0210** [comment]
Thank you！I'll try it as you say.

谢谢！我按你说的来操作一次.

**Comment by lw0210** [comment]
Thank  you！I'll try it as you say.

谢谢！我按你说的来操作一次. @guangkaixu
