### ISSUE TITLE
About intrinsic usage in mix dataset training

### ISSUE THREAD

**Issue by mzy97** [aim-uofa/AdelaiDepth#4]
In normal loss, you constructed predicted normal map from point cloud (generated by aligned depth). If mix dataset in training, there will be several intrinsics in a batch, how to manage these intrinsics to let it be used in right depth map in training stage? And when mixing web stereo dataset, there is no intrinsic, how to construct point cloud from these data?

thank you

**Comment by YvanYin** [comment]
1) Manage intrinsics in a batch.
  -- When I load the each data in a batch, I will load depth/rgb/intrinsics at the same time and save them in a dict. It can make sure that the depth and intrinsics are paired.
2) Point cloud for the web stereo data.
 -- For the webstereo data, we will not enforce any geometry loss on them. Therefore, we don't need to reconstruct the point cloud on them.
