### ISSUE TITLE
python3: can't open file 'LeReS/tools/test_depth.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by milkliker** [aim-uofa/AdelaiDepth#42]
in the notebook: LeReS/tools/test_depth.py not exist

**Comment by guangkaixu** [comment]
Hi, the path to test_depth.py has been changed to "LeReS/Minist_Test/tools/test_depth.py". The code in the notebook has not been updated yet, so we recommend you to follow the [README.md](https://github.com/aim-uofa/AdelaiDepth/blob/main/LeReS/README.md).

**Comment by xiaoguo426** [comment]
> Hi, the path to test_depth.py has been changed to "LeReS/Minist_Test/tools/test_depth.py". The code in the notebook has not been updated yet, so we recommend you to follow the [README.md](https://github.com/aim-uofa/AdelaiDepth/blob/main/LeReS/README.md).

Will it be updated in the future? I had the same problem running in colab

**Comment by guangkaixu** [comment]
@xiaoguo426 We will update the code in the colab later after I finished my deadlines. Thanks for your following and I will remind you after updating the colab code.

**Comment by IgorKasianenko** [comment]
Colab is still broken
```!python3 LeReS/Minist_Test/tools/test_depth.py --load_ckpt res101.pth --backbone resnext101```
returns
```
/env/python:/content/AdelaiDepth/LeReS
/content/AdelaiDepth
Traceback (most recent call last):
  File "LeReS/Minist_Test/tools/test_depth.py", line 9, in <module>
    from lib.multi_depth_model_woauxi import RelDepthModel
ModuleNotFoundError: No module named 'lib'
```

**Comment by IgorKasianenko** [comment]
@EllieFar no, if repository owner doesn't provide fixes there is nothing we can do

**Comment by guangkaixu** [comment]
@milkliker @xiaoguo426 @IgorKasianenko @EllieFar Sorry for the late response, bug has been fixed in https://github.com/aim-uofa/AdelaiDepth/issues/65#issuecomment-1492816706.
