### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by lw0210** [aim-uofa/AdelaiDepth#48]
Dear,
I download your dataset (taskeconomy, diversedepth, hwrsi and holopix50k) by running sh Download_ data. sh, and run your recently updated code. I can run sh train_ demo. sh, but cannot run sh train.sh. I modify the parameter dataset_ list in train.sh (only HWRSI is left，others are not allowed), you can run for a while and then report an error:

AttributeError: 'NoneType' object has no attribute 'lower'

I think it is the lack of content in the datasets.Can you check your dataset？Thanks！

**Comment by guangkaixu** [comment]
Hi, it seems there exists some invalid file paths in the annotation files. I will double-check them and release as soon as possible. Thanks!

**Comment by lw0210** [comment]
Thanks！Thank you. Maybe my network is unstable ，so can't downloaded it completely.I'm downloading it again and I get a&nbsp; reply from others saying that "two of them cannot be used during val (hwrsi and holopix50k) because the read data depth and disp are inconsistent".




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guangkai ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aim-uofa/AdelaiDepth] AttributeError: &#39;NoneType&#39; object has no attribute &#39;lower&#39; (Issue #48)





 
Hi, it seems there exists some invalid file paths in the annotation files. I will double-check them and release as soon as possible. Thanks!

**Comment by guangkaixu** [comment]
@lw0210 This bug happened because the validation datasets should contain depth images rather than disparity images, which have been fixed just now. Please download the latest annotation files of taskonomy in [download_data.sh](https://github.com/aim-uofa/AdelaiDepth/blob/main/LeReS/download_data.sh) pull the latest code. Thank you!

**Comment by lw0210** [comment]
Thank you. I'll try again






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aim-uofa/AdelaiDepth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aim-uofa/AdelaiDepth] AttributeError: 'NoneType' object has no attribute 'lower' (Issue #48)





 
@lw0210 This bug happened because the validation datasets should contain depth images rather than disparity images, which have been fixed just now. Please download the latest annotation files of taskonomy in download_data.sh pull the latest code. Thank you!
