### ISSUE TITLE
Correct initial FoV?

### ISSUE THREAD

**Issue by cr333** [aim-uofa/AdelaiDepth#5]
https://github.com/aim-uofa/AdelaiDepth/blob/5deec71ead739916f78adf728eb1ce3978066408/LeReS/tools/test_shape.py#L66-L67

Section 3.1 in your paper mentions an initial FoV of 60°, not 80°.
Figure 4 (right) also suggests that using an initial FoV of 80° would be sub-optimal.

Could you please clarify and/or update your code to be consistent with the paper? Thanks.

**Comment by YvanYin** [comment]
Thank you for pointing out this issue. Actually, the proposed FOV can be in the range of [60, 80] degree. I have updated the code to make it consistent to the paper.
