### ISSUE TITLE
360 point cloud animation video

### ISSUE THREAD

**Issue by jaykar21** [aim-uofa/AdelaiDepth#53]
Hi, 

Thanks for the great work!

Is there a visualization script to generate the 360 point cloud animation video or did you use a specific tool for this? 

Thanks!

**Comment by guangkaixu** [comment]
Hi, I just uploaded the file rotate_pcd.py, you can use and change the parameters of rendering [here(https://github.com/aim-uofa/AdelaiDepth/blob/9bee191c76a87f8c99580d68fb1c44667d728fdb/LeReS/Minist_Test/tools/rotate_pcd.py#L71)]
