### ISSUE TITLE
Strange size of output files for train

### ISSUE THREAD

**Issue by ori30ffs** [aim-uofa/AdelaiDepth#54]
Hello, I tried to use your train_demo.sh script. After 200 epoch I don't have any progress on test dataset. 
I attached files with my environment, log and output folder.
Could you help me, what I'm doing wrong?
[Oct11-14-37-36_MSISPlap03.txt](https://github.com/aim-uofa/AdelaiDepth/files/9756337/Oct11-14-37-36_MSISPlap03.txt)
![Untitled](https://user-images.githubusercontent.com/11530290/195106681-4c3844e7-7254-451c-a339-835ece3ee08a.png)
[env.txt](https://github.com/aim-uofa/AdelaiDepth/files/9756501/env.txt)
![image](https://user-images.githubusercontent.com/11530290/195189292-577b6bf4-3992-4334-836c-f7a2d70c1d70.png)

**Comment by guangkaixu** [comment]
The train_demo.sh is only performed to ensure the accurate environment installation, which is only trained on 5 RGB-D pairs. To validate more frequently, you can change the parameter val_step to be small.
