### ISSUE TITLE
cannot import name 'sparse_collate_fn' from 'torch_sparse.utils'

### ISSUE THREAD

**Issue by wty3515** [aim-uofa/AdelaiDepth#55]
hello ,I can't find those two function in torch_sparse.utils and pytorch official doc. I have checked this file，I've looked into this file, but there are none of these two functions
![2022-10-19 10-11-11 的屏幕截图](https://user-images.githubusercontent.com/96370831/196580908-43c7a6dc-650a-4d1b-a4e5-1cf567d1f4da.png)

![2022-10-19 10-08-38 的屏幕截图](https://user-images.githubusercontent.com/96370831/196580836-2d4737c2-3352-497c-83b4-09667f3f3578.png)

Could you help me, what should I do?

**Comment by guangkaixu** [comment]
The sparse_collate_fn is [here](https://github.com/mit-han-lab/torchsparse/blob/74099d10a51c71c14318bce63d6421f698b24f24/torchsparse/utils/collate.py#L40) and the sparse_quantize is [here](https://github.com/mit-han-lab/torchsparse/blob/038e6c22a177415da9bf3c907e26d3815f5c66f9/torchsparse/utils/quantize.py#L24).
