### ISSUE TITLE
#@title Download results

### ISSUE THREAD

**Issue by anupkumarmridha** [aim-uofa/AdelaiDepth#56]
/content/AdelaiDepth/LeReS/test_images

zip error: Nothing to do! (result.zip)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-9-2b2f09c79455>](https://localhost:8080/#) in <module>
      3 get_ipython().run_line_magic('cd', '/content/AdelaiDepth/LeReS/test_images/')
      4 get_ipython().system('find outputs/ -name "*-depth_raw.png" | zip -r result.zip -@')
----> 5 files.download("result.zip")

[/usr/local/lib/python3.7/dist-packages/google/colab/files.py](https://localhost:8080/#) in download(filename)
    207   if not _os.path.exists(filename):
    208     msg = 'Cannot find file: {}'.format(filename)
--> 209     raise FileNotFoundError(msg)  # pylint: disable=undefined-variable
    210 
    211   comm_manager = _IPython.get_ipython().kernel.comm_manager

FileNotFoundError: Cannot find file: result.zip

**Comment by guangkaixu** [comment]
The code in google cobal has not been updated yet. Please use the code in the github, and we'll update the code of colab later. Thank you!

**Comment by guangkaixu** [comment]
Bug has been fixed in https://github.com/aim-uofa/AdelaiDepth/issues/65#issuecomment-1492816706.
