### ISSUE TITLE
Where can I find tools/test_depth.py and tools/test_shape.py?

### ISSUE THREAD

**Issue by tway24** [aim-uofa/AdelaiDepth#64]
As mentioned in https://github.com/aim-uofa/AdelaiDepth/tree/main/LeReS#quick-start-inference, I can't find tools/test_depth.py and tools/test_shape.py. Could you please direct me?

**Comment by guangkaixu** [comment]
Hi, the two python files are under "AdelaiDepth/LeReS/Minist_Test"[https://github.com/aim-uofa/AdelaiDepth/tree/main/LeReS/Minist_Test/tools].
