### ISSUE TITLE
Infinit focal length!!!

### ISSUE THREAD

**Issue by jfsunx** [aim-uofa/AdelaiDepth#67]
output：
```
processing (0000)-th image... /content/drive/MyDrive/AdelaiDepth/LeReS/Minist_Test/test_images/5.jpg
Infinit focal length!!!
```

What does' Infinit focal length!!! 'mean for example images and my own images?

**Comment by guangkaixu** [comment]
It means the predicted focal length is too large (larger than 1e5). Have you visualized the output point cloud, and is it visually correct? If not, please check if you have loaded the checkpoint. Or you can try to ignore the "if" of https://github.com/aim-uofa/AdelaiDepth/blob/9bee191c76a87f8c99580d68fb1c44667d728fdb/LeReS/Minist_Test/lib/test_utils.py#L147 and follow the "else" code.
