### ISSUE TITLE
Error occurred in LeReS

### ISSUE THREAD

**Issue by ZackChenUuu** [aim-uofa/AdelaiDepth#68]
![image](https://user-images.githubusercontent.com/125977225/230531044-f079abca-5e34-4731-8179-7e0c258b0090.png)
When I try to test 3D reconstruction from a single image by using "LeReS" code, the above error occurred. Could you offer some help please? If it is possible,may you explain the type of these two parameters('coords' and 'voxel_size'), are they numpy.ndarray or float or something else?And what are the meanings of these parameters?
Thx a lot !!!

**Comment by guangkaixu** [comment]
@ZackChenUuu Hi, I can run ```python ./tools/test_shape.py --load-ckpt res50.pth --backbone resnet50``` successfully, please check that you are using the latest code and the correct environment. If you fail to install torchsparse with ```pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.2.0```, you can download the file of torchsparse1.2.0 from https://github.com/mit-han-lab/torchsparse/tags, and install it with ```python setup.py install```.
