### ISSUE TITLE
Code Execution Result

### ISSUE THREAD

**Issue by Minisal** [aim-uofa/AdelaiDepth#7]
The work is excellent. But the depth maps I got after executing the code according to the README is completely
 inconsistent with the results in the paper. Is the uploaded model different?

<img src="https://user-images.githubusercontent.com/48203123/119311599-dab63f00-bca3-11eb-86d2-3476aa8aa4a3.jpg" alt="7-color" width="200"/><img src="https://user-images.githubusercontent.com/48203123/119310987-18ff2e80-bca3-11eb-8051-c08f8db8de1f.png" alt="7-depth" width="200"/>

<img src="https://user-images.githubusercontent.com/48203123/119311871-2ff25080-bca4-11eb-8282-3ca071784a02.jpg" alt="6-color" width="200"/><img src="https://user-images.githubusercontent.com/48203123/119310981-17356b00-bca3-11eb-8c69-a95157648cf3.png" alt="6-depth" width="200"/>

**Comment by YvanYin** [comment]
Have you successfully load the model weight? Could you check that? Also, which version of PyTorch do you use?

**Comment by Minisal** [comment]
Thank you for your response! I have solved this problem.
When I configure the environment in Clion and execute the project, there is no error. But when I enter the command directly on the terminal, there is an error: ModuleNotFoundError: No module named 'lib'.
After I changed the order of importing, the code results got the correct depth map. 
``` python
import os
import sys
sys.path.insert(1, os.path.abspath(".")) # insert the current directory 
from lib.multi_depth_model_woauxi import RelDepthModel
from lib.net_tools import load_ckpt
```
