### ISSUE TITLE
how to generate depth data like you provide?

### ISSUE THREAD

**Issue by yangtf-210310** [aim-uofa/AdelaiDepth#70]
Hi，I want training model use myself datasets, how to generate depth data like you provide?

**Comment by guangkaixu** [comment]
@yangtf-210310 Hi, sorry for the late response. If you would like to train the depth model on your own datasets, please generate an ```annotation.json``` file, which contains a list, and each component in the list is a dict, the dict contains relative path of ```rgb_path``` and ```depth_path```. For example, the test_annotations.json of diversedepth_annotations in https://github.com/aim-uofa/AdelaiDepth/blob/9bee191c76a87f8c99580d68fb1c44667d728fdb/LeReS/download_data.sh#L21 is shown as follows:

```
[{"rgb_path": "taskonomy/rgbs/akiak/point_146_view_1_domain_rgb.png", "depth_path": "taskonomy/depths/akiak/point_146_view_1_domain_depth_zbuffer.png"}, {"rgb_path": "taskonomy/rgbs/akiak/point_80_view_5_domain_rgb.png", "depth_path": "taskonomy/depths/akiak/point_80_view_5_domain_depth_zbuffer.png"}, ...]
```

change the ```quality_flg``` of each dataset in https://github.com/aim-uofa/AdelaiDepth/blob/9bee191c76a87f8c99580d68fb1c44667d728fdb/LeReS/Train/data/multi_dataset.py#L193 as follows:
1) If the quality of depth sensor is reliable to supervise virtual normal, set it to 3;
2) If not so reliable, set it to 2;
3) If obtained from web images or unreliable pseudo labels, set it to 1, which only supervises the relative depth relation.
