### ISSUE TITLE
Need Pretrained Parameters

### ISSUE THREAD

**Issue by BigEarAsk** [aim-uofa/AdelaiDepth#72]
Hi, I am desired to obtain the **pretrained parameters** of '**shift model**' and '**focal model**'.
These two models are used in your 'shape_test.py' file.
Could you please help me?
Looking forward to your reply!

**Comment by guangkaixu** [comment]
Random init will be okay.

**Comment by wangty537** [comment]
hi, would you like to share the datasets on google drive or baidu , as the author's datasets link doesnot work. thank you
