### ISSUE TITLE
Visualize with texture.

### ISSUE THREAD

**Issue by JohnG0024** [aim-uofa/AdelaiDepth#74]
Hi, is there a way to visualize the point cloud or mesh with texture? It's really hard to tell the mapping or accuracy. 
![cap3](https://github.com/aim-uofa/AdelaiDepth/assets/70065447/07f7a7ef-1e0d-4517-9f61-9f674b7c2f29)

**Comment by guangkaixu** [comment]
The information of color and point has been recorded in https://github.com/aim-uofa/AdelaiDepth/blob/c57ed5cec49222da7007035eb3d8666d47a2b88f/LeReS/Minist_Test/lib/test_utils.py#L213C15-L213C15. You can check the visualization software and we recommend using the MeshLab.
