### ISSUE TITLE
Is there a different version of torchsparse that is used? 

### ISSUE THREAD

**Issue by sabraha2** [aim-uofa/AdelaiDepth#9]
Installed the latest version of torchsparse (v1.4.0)  and when running the 3D reconstruction command get the following errors: 

`from torchsparse.point_tensor import PointTensor`
`ModuleNotFoundError: No module named 'torchsparse.point_tensor`

I noticed in the `torchsparse` repo, `PointTensor` was found in `torchsparse.tensor`. 

But also received the error: 
`from torchsparse.utils.kernel_region import *`
`ModuleNotFoundError: No module named 'torchsparse.utils.kernel_region'` and noticed I could not find `kernel_region` and was wondering if a different version was used? 

Excellent work by the way! :)

**Comment by mkocabas** [comment]
Try to checkout [this commit](https://github.com/mit-han-lab/torchsparse/tree/da0abb33fea2522ae8b71cb4ec30a4e461fa58e8) and install it using `python setup.py install`.

**Comment by YvanYin** [comment]
@sabraha2 Have you solved the issue?
@mkocabas thx.

**Comment by sabraha2** [comment]
The commit @mkocabas pointed to is the correct version! Thank you both so much! :) 

In case anyone else runs into this problem, can also just install by running: 
`pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.2.0`

**Comment by YangLI-aftermath** [comment]
> The commit @mkocabas pointed to is the correct version! Thank you both so much! :)
> 
> In case anyone else runs into this problem, can easily install by running: `pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.2.0`

I tried this but it didn't work. But the commit pointed by @mkocabas works well.
